display_name: Mitveepn

packager: mitveepn
packagerEmail: support@mitveepn.work
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - Mitveepn
  - Clash
  - ClashMeta
  - Proxy

generic_name: Mitveepn

group: Applications/Internet

startup_notify: true