import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'text.dart';

/// Resolves a country flag from location information commonly included in
/// proxy names (ISO 3166-1 alpha-2/alpha-3 codes, country names, and flag
/// emoji). The returned value is the alpha-3 filename used by the bundled
/// country-flag-icons SVG assets.
String? countryFlagCodeForName(String name) {
  final normalized = name.trim().toLowerCase();
  if (normalized.isEmpty) return null;

  // Prefer an explicit flag emoji when a subscription already includes one.
  final emojiCode = _countryCodeFromFlagEmoji(name);
  if (emojiCode != null) {
    final asset = _countryCodesToAssets[emojiCode];
    if (asset != null) return asset;
  }

  // Match a country name before short code tokens so that e.g. "US" in a
  // provider label cannot accidentally hide a more specific country name.
  String? matchedCountry;
  for (final entry in _countryNamesToAssets.entries) {
    if ((matchedCountry == null || entry.key.length > matchedCountry.length) &&
        _hasWord(normalized, entry.key)) {
      matchedCountry = entry.key;
    }
  }
  if (matchedCountry != null) {
    return _countryNamesToAssets[matchedCountry];
  }

  // Codes are intentionally matched only at token boundaries. This avoids
  // treating ordinary words such as "Singapore" or "direct" as country codes.
  final tokenPattern = RegExp(r'(?<![a-z])([a-z]{2,3})(?![a-z])');
  for (final match in tokenPattern.allMatches(normalized)) {
    final asset = _countryCodesToAssets[match.group(1)!.toUpperCase()];
    if (asset != null) return asset;
  }

  // A few providers use compact labels such as "US01" or "JP-Tokyo".
  final prefix = RegExp(r'^([a-z]{2,3})(?=[0-9_-])').firstMatch(normalized);
  if (prefix != null) {
    return _countryCodesToAssets[prefix.group(1)!.toUpperCase()];
  }
  return null;
}

bool _hasWord(String value, String word) {
  final escaped = RegExp.escape(word);
  return RegExp('(?<![a-z])$escaped(?![a-z])').hasMatch(value);
}

String? _countryCodeFromFlagEmoji(String value) {
  final codePoints = value.runes.toList();
  for (var i = 0; i + 1 < codePoints.length; i++) {
    final first = codePoints[i];
    final second = codePoints[i + 1];
    if (first >= 0x1F1E6 &&
        first <= 0x1F1FF &&
        second >= 0x1F1E6 &&
        second <= 0x1F1FF) {
      return String.fromCharCodes([
        first - 0x1F1E6 + 0x41,
        second - 0x1F1E6 + 0x41,
      ]);
    }
  }
  return null;
}

/// Displays a node name with its country flag, when the name contains
/// recognizable country information.
class CountryFlagText extends StatelessWidget {
  final String text;
  final TextStyle? style;
  final int? maxLines;
  final TextOverflow? overflow;
  final double flagWidth;
  final double flagHeight;

  const CountryFlagText(
    this.text, {
    super.key,
    this.maxLines,
    this.overflow,
    this.style,
    this.flagWidth = 20,
    this.flagHeight = 14,
  });

  @override
  Widget build(BuildContext context) {
    final flagCode = countryFlagCodeForName(text);
    final nameText = EmojiText(
      text,
      maxLines: maxLines,
      overflow: overflow,
      style: style,
    );
    if (flagCode == null) return nameText;

    return Row(
      mainAxisSize: MainAxisSize.max,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        ClipRRect(
          borderRadius: BorderRadius.circular(2),
          child: SvgPicture.asset(
            'assets/images/flags/$flagCode.svg',
            width: flagWidth,
            height: flagHeight,
            fit: BoxFit.cover,
            semanticsLabel: 'Country flag',
          ),
        ),
        const SizedBox(width: 5),
        Flexible(child: nameText),
      ],
    );
  }
}

/// ISO alpha-2 and alpha-3 codes mapped to the corresponding alpha-3 asset.
const Map<String, String> _countryCodesToAssets = {
  'AND': 'and',
  'AD': 'and',
  'ARE': 'are',
  'AE': 'are',
  'AFG': 'afg',
  'AF': 'afg',
  'ATG': 'atg',
  'AG': 'atg',
  'AIA': 'aia',
  'AI': 'aia',
  'ALB': 'alb',
  'AL': 'alb',
  'ARM': 'arm',
  'AM': 'arm',
  'AGO': 'ago',
  'AO': 'ago',
  'ARG': 'arg',
  'AR': 'arg',
  'ASM': 'asm',
  'AS': 'asm',
  'AUT': 'aut',
  'AT': 'aut',
  'AUS': 'aus',
  'AU': 'aus',
  'ABW': 'abw',
  'AW': 'abw',
  'ALA': 'ala',
  'AX': 'ala',
  'AZE': 'aze',
  'AZ': 'aze',
  'BIH': 'bih',
  'BA': 'bih',
  'BRB': 'brb',
  'BB': 'brb',
  'BGD': 'bgd',
  'BD': 'bgd',
  'BEL': 'bel',
  'BE': 'bel',
  'BFA': 'bfa',
  'BF': 'bfa',
  'BGR': 'bgr',
  'BG': 'bgr',
  'BHR': 'bhr',
  'BH': 'bhr',
  'BDI': 'bdi',
  'BI': 'bdi',
  'BEN': 'ben',
  'BJ': 'ben',
  'BLM': 'blm',
  'BL': 'blm',
  'BMU': 'bmu',
  'BM': 'bmu',
  'BRN': 'brn',
  'BN': 'brn',
  'BOL': 'bol',
  'BO': 'bol',
  'BES': 'bes',
  'BQ': 'bes',
  'BRA': 'bra',
  'BR': 'bra',
  'BHS': 'bhs',
  'BS': 'bhs',
  'BTN': 'btn',
  'BT': 'btn',
  'BVT': 'bvt',
  'BV': 'bvt',
  'BWA': 'bwa',
  'BW': 'bwa',
  'BLR': 'blr',
  'BY': 'blr',
  'BLZ': 'blz',
  'BZ': 'blz',
  'CAN': 'can',
  'CA': 'can',
  'CCK': 'cck',
  'CC': 'cck',
  'COD': 'cod',
  'CD': 'cod',
  'CAF': 'caf',
  'CF': 'caf',
  'COG': 'cog',
  'CG': 'cog',
  'CHE': 'che',
  'CH': 'che',
  'CIV': 'civ',
  'CI': 'civ',
  'COK': 'cok',
  'CK': 'cok',
  'CHL': 'chl',
  'CL': 'chl',
  'CMR': 'cmr',
  'CM': 'cmr',
  'CHN': 'chn',
  'CN': 'chn',
  'COL': 'col',
  'CO': 'col',
  'CRI': 'cri',
  'CR': 'cri',
  'CUB': 'cub',
  'CU': 'cub',
  'CPV': 'cpv',
  'CV': 'cpv',
  'CUW': 'cuw',
  'CW': 'cuw',
  'CXR': 'cxr',
  'CX': 'cxr',
  'CYP': 'cyp',
  'CY': 'cyp',
  'CZE': 'cze',
  'CZ': 'cze',
  'DEU': 'deu',
  'DE': 'deu',
  'DJI': 'dji',
  'DJ': 'dji',
  'DNK': 'dnk',
  'DK': 'dnk',
  'DMA': 'dma',
  'DM': 'dma',
  'DOM': 'dom',
  'DO': 'dom',
  'DZA': 'dza',
  'DZ': 'dza',
  'ECU': 'ecu',
  'EC': 'ecu',
  'EST': 'est',
  'EE': 'est',
  'EGY': 'egy',
  'EG': 'egy',
  'ERI': 'eri',
  'ER': 'eri',
  'ESP': 'esp',
  'ES': 'esp',
  'ETH': 'eth',
  'ET': 'eth',
  'FIN': 'fin',
  'FI': 'fin',
  'FJI': 'fji',
  'FJ': 'fji',
  'FLK': 'flk',
  'FK': 'flk',
  'FSM': 'fsm',
  'FM': 'fsm',
  'FRO': 'fro',
  'FO': 'fro',
  'FRA': 'fra',
  'FR': 'fra',
  'GAB': 'gab',
  'GA': 'gab',
  'GBR': 'gbr',
  'GB': 'gbr',
  'GRD': 'grd',
  'GD': 'grd',
  'GEO': 'geo',
  'GE': 'geo',
  'GUF': 'guf',
  'GF': 'guf',
  'GGY': 'ggy',
  'GG': 'ggy',
  'GHA': 'gha',
  'GH': 'gha',
  'GIB': 'gib',
  'GI': 'gib',
  'GRL': 'grl',
  'GL': 'grl',
  'GMB': 'gmb',
  'GM': 'gmb',
  'GIN': 'gin',
  'GN': 'gin',
  'GLP': 'glp',
  'GP': 'glp',
  'GNQ': 'gnq',
  'GQ': 'gnq',
  'GRC': 'grc',
  'GR': 'grc',
  'SGS': 'sgs',
  'GS': 'sgs',
  'GTM': 'gtm',
  'GT': 'gtm',
  'GUM': 'gum',
  'GU': 'gum',
  'GNB': 'gnb',
  'GW': 'gnb',
  'GUY': 'guy',
  'GY': 'guy',
  'HKG': 'hkg',
  'HK': 'hkg',
  'HMD': 'hmd',
  'HM': 'hmd',
  'HND': 'hnd',
  'HN': 'hnd',
  'HRV': 'hrv',
  'HR': 'hrv',
  'HTI': 'hti',
  'HT': 'hti',
  'HUN': 'hun',
  'HU': 'hun',
  'IDN': 'idn',
  'ID': 'idn',
  'IRL': 'irl',
  'IE': 'irl',
  'ISR': 'isr',
  'IL': 'isr',
  'IMN': 'imn',
  'IM': 'imn',
  'IND': 'ind',
  'IN': 'ind',
  'IOT': 'iot',
  'IO': 'iot',
  'IRQ': 'irq',
  'IQ': 'irq',
  'IRN': 'irn',
  'IR': 'irn',
  'ISL': 'isl',
  'IS': 'isl',
  'ITA': 'ita',
  'IT': 'ita',
  'JEY': 'jey',
  'JE': 'jey',
  'JAM': 'jam',
  'JM': 'jam',
  'JOR': 'jor',
  'JO': 'jor',
  'JPN': 'jpn',
  'JP': 'jpn',
  'KEN': 'ken',
  'KE': 'ken',
  'KGZ': 'kgz',
  'KG': 'kgz',
  'KHM': 'khm',
  'KH': 'khm',
  'KIR': 'kir',
  'KI': 'kir',
  'COM': 'com',
  'KM': 'com',
  'KNA': 'kna',
  'KN': 'kna',
  'PRK': 'prk',
  'KP': 'prk',
  'KOR': 'kor',
  'KR': 'kor',
  'KWT': 'kwt',
  'KW': 'kwt',
  'CYM': 'cym',
  'KY': 'cym',
  'KAZ': 'kaz',
  'KZ': 'kaz',
  'LAO': 'lao',
  'LA': 'lao',
  'LBN': 'lbn',
  'LB': 'lbn',
  'LCA': 'lca',
  'LC': 'lca',
  'LIE': 'lie',
  'LI': 'lie',
  'LKA': 'lka',
  'LK': 'lka',
  'LBR': 'lbr',
  'LR': 'lbr',
  'LSO': 'lso',
  'LS': 'lso',
  'LTU': 'ltu',
  'LT': 'ltu',
  'LUX': 'lux',
  'LU': 'lux',
  'LVA': 'lva',
  'LV': 'lva',
  'LBY': 'lby',
  'LY': 'lby',
  'MAR': 'mar',
  'MA': 'mar',
  'MCO': 'mco',
  'MC': 'mco',
  'MDA': 'mda',
  'MD': 'mda',
  'MNE': 'mne',
  'ME': 'mne',
  'MAF': 'maf',
  'MF': 'maf',
  'MDG': 'mdg',
  'MG': 'mdg',
  'MHL': 'mhl',
  'MH': 'mhl',
  'MKD': 'mkd',
  'MK': 'mkd',
  'MLI': 'mli',
  'ML': 'mli',
  'MMR': 'mmr',
  'MM': 'mmr',
  'MNG': 'mng',
  'MN': 'mng',
  'MAC': 'mac',
  'MO': 'mac',
  'MNP': 'mnp',
  'MP': 'mnp',
  'MTQ': 'mtq',
  'MQ': 'mtq',
  'MRT': 'mrt',
  'MR': 'mrt',
  'MSR': 'msr',
  'MS': 'msr',
  'MLT': 'mlt',
  'MT': 'mlt',
  'MUS': 'mus',
  'MU': 'mus',
  'MDV': 'mdv',
  'MV': 'mdv',
  'MWI': 'mwi',
  'MW': 'mwi',
  'MEX': 'mex',
  'MX': 'mex',
  'MYS': 'mys',
  'MY': 'mys',
  'MOZ': 'moz',
  'MZ': 'moz',
  'NAM': 'nam',
  'NA': 'nam',
  'NCL': 'ncl',
  'NC': 'ncl',
  'NER': 'ner',
  'NE': 'ner',
  'NFK': 'nfk',
  'NF': 'nfk',
  'NGA': 'nga',
  'NG': 'nga',
  'NIC': 'nic',
  'NI': 'nic',
  'NLD': 'nld',
  'NL': 'nld',
  'NOR': 'nor',
  'NO': 'nor',
  'NPL': 'npl',
  'NP': 'npl',
  'NRU': 'nru',
  'NR': 'nru',
  'NIU': 'niu',
  'NU': 'niu',
  'NZL': 'nzl',
  'NZ': 'nzl',
  'OMN': 'omn',
  'OM': 'omn',
  'PAN': 'pan',
  'PA': 'pan',
  'PER': 'per',
  'PE': 'per',
  'PYF': 'pyf',
  'PF': 'pyf',
  'PNG': 'png',
  'PG': 'png',
  'PHL': 'phl',
  'PH': 'phl',
  'PAK': 'pak',
  'PK': 'pak',
  'POL': 'pol',
  'PL': 'pol',
  'SPM': 'spm',
  'PM': 'spm',
  'PCN': 'pcn',
  'PN': 'pcn',
  'PRI': 'pri',
  'PR': 'pri',
  'PSE': 'pse',
  'PS': 'pse',
  'PRT': 'prt',
  'PT': 'prt',
  'PLW': 'plw',
  'PW': 'plw',
  'PRY': 'pry',
  'PY': 'pry',
  'QAT': 'qat',
  'QA': 'qat',
  'REU': 'reu',
  'RE': 'reu',
  'ROU': 'rou',
  'RO': 'rou',
  'SRB': 'srb',
  'RS': 'srb',
  'RUS': 'rus',
  'RU': 'rus',
  'RWA': 'rwa',
  'RW': 'rwa',
  'SAU': 'sau',
  'SA': 'sau',
  'SLB': 'slb',
  'SB': 'slb',
  'SYC': 'syc',
  'SC': 'syc',
  'SDN': 'sdn',
  'SD': 'sdn',
  'SWE': 'swe',
  'SE': 'swe',
  'SGP': 'sgp',
  'SG': 'sgp',
  'SHN': 'shn',
  'SH': 'shn',
  'SVN': 'svn',
  'SI': 'svn',
  'SJM': 'sjm',
  'SJ': 'sjm',
  'SVK': 'svk',
  'SK': 'svk',
  'SLE': 'sle',
  'SL': 'sle',
  'SMR': 'smr',
  'SM': 'smr',
  'SEN': 'sen',
  'SN': 'sen',
  'SOM': 'som',
  'SO': 'som',
  'SUR': 'sur',
  'SR': 'sur',
  'SSD': 'ssd',
  'SS': 'ssd',
  'STP': 'stp',
  'ST': 'stp',
  'SLV': 'slv',
  'SV': 'slv',
  'SXM': 'sxm',
  'SX': 'sxm',
  'SYR': 'syr',
  'SY': 'syr',
  'SWZ': 'swz',
  'SZ': 'swz',
  'TCA': 'tca',
  'TC': 'tca',
  'TCD': 'tcd',
  'TD': 'tcd',
  'ATF': 'atf',
  'TF': 'atf',
  'TGO': 'tgo',
  'TG': 'tgo',
  'THA': 'tha',
  'TH': 'tha',
  'TJK': 'tjk',
  'TJ': 'tjk',
  'TKL': 'tkl',
  'TK': 'tkl',
  'TLS': 'tls',
  'TL': 'tls',
  'TKM': 'tkm',
  'TM': 'tkm',
  'TUN': 'tun',
  'TN': 'tun',
  'TON': 'ton',
  'TO': 'ton',
  'TUR': 'tur',
  'TR': 'tur',
  'TTO': 'tto',
  'TT': 'tto',
  'TUV': 'tuv',
  'TV': 'tuv',
  'TWN': 'twn',
  'TW': 'twn',
  'TZA': 'tza',
  'TZ': 'tza',
  'UKR': 'ukr',
  'UA': 'ukr',
  'UGA': 'uga',
  'UG': 'uga',
  'UMI': 'umi',
  'UM': 'umi',
  'USA': 'usa',
  'US': 'usa',
  'URY': 'ury',
  'UY': 'ury',
  'UZB': 'uzb',
  'UZ': 'uzb',
  'VAT': 'vat',
  'VA': 'vat',
  'VCT': 'vct',
  'VC': 'vct',
  'VEN': 'ven',
  'VE': 'ven',
  'VGB': 'vgb',
  'VG': 'vgb',
  'VIR': 'vir',
  'VI': 'vir',
  'VNM': 'vnm',
  'VN': 'vnm',
  'VUT': 'vut',
  'VU': 'vut',
  'WLF': 'wlf',
  'WF': 'wlf',
  'WSM': 'wsm',
  'WS': 'wsm',
  'YEM': 'yem',
  'YE': 'yem',
  'MYT': 'myt',
  'YT': 'myt',
  'ZAF': 'zaf',
  'ZA': 'zaf',
  'ZMB': 'zmb',
  'ZM': 'zmb',
  'ZWE': 'zwe',
  'ZW': 'zwe',
};

/// Country names from country-flag-icons' countries.json.
const Map<String, String> _countryNamesToAssets = {
  "afghanistan": 'afg',
  "åland islands": 'ala',
  "albania": 'alb',
  "algeria": 'dza',
  "american samoa": 'asm',
  "andorra": 'and',
  "angola": 'ago',
  "anguilla": 'aia',
  "antigua and barbuda": 'atg',
  "argentina": 'arg',
  "armenia": 'arm',
  "aruba": 'abw',
  "australia": 'aus',
  "austria": 'aut',
  "azerbaijan": 'aze',
  "bahamas": 'bhs',
  "bahrain": 'bhr',
  "bangladesh": 'bgd',
  "barbados": 'brb',
  "belarus": 'blr',
  "belgium": 'bel',
  "belize": 'blz',
  "benin": 'ben',
  "bermuda": 'bmu',
  "bhutan": 'btn',
  "bolivia - plurinational state of": 'bol',
  "bonaire - sint eustatius and saba": 'bes',
  "bosnia and herzegovina": 'bih',
  "botswana": 'bwa',
  "brazil": 'bra',
  "british indian ocean territory": 'iot',
  "brunei darussalam": 'brn',
  "bulgaria": 'bgr',
  "burkina faso": 'bfa',
  "burundi": 'bdi',
  "cabo verde": 'cpv',
  "cambodia": 'khm',
  "cameroon": 'cmr',
  "canada": 'can',
  "cayman islands": 'cym',
  "central african republic": 'caf',
  "chad": 'tcd',
  "chile": 'chl',
  "china": 'chn',
  "christmas island": 'cxr',
  "cocos (keeling) islands": 'cck',
  "colombia": 'col',
  "comoros": 'com',
  "congo": 'cog',
  "congo - democratic republic of the": 'cod',
  "cook islands": 'cok',
  "costa rica": 'cri',
  "côte d'ivoire": 'civ',
  "croatia": 'hrv',
  "cuba": 'cub',
  "curaçao": 'cuw',
  "cyprus": 'cyp',
  "czechia": 'cze',
  "denmark": 'dnk',
  "djibouti": 'dji',
  "dominica": 'dma',
  "dominican republic": 'dom',
  "ecuador": 'ecu',
  "egypt": 'egy',
  "el salvador": 'slv',
  "equatorial guinea": 'gnq',
  "eritrea": 'eri',
  "estonia": 'est',
  "eswatini": 'swz',
  "ethiopia": 'eth',
  "falkland islands (malvinas)": 'flk',
  "faroe islands": 'fro',
  "fiji": 'fji',
  "finland": 'fin',
  "france": 'fra',
  "french polynesia": 'pyf',
  "french southern territories": 'atf',
  "gabon": 'gab',
  "gambia": 'gmb',
  "georgia": 'geo',
  "germany": 'deu',
  "ghana": 'gha',
  "gibraltar": 'gib',
  "greece": 'grc',
  "greenland": 'grl',
  "grenada": 'grd',
  "guadeloupe": 'glp',
  "guam": 'gum',
  "guatemala": 'gtm',
  "guernsey": 'ggy',
  "guinea": 'gin',
  "guinea-bissau": 'gnb',
  "guyana": 'guy',
  "haiti": 'hti',
  "holy see": 'vat',
  "honduras": 'hnd',
  "hong kong": 'hkg',
  "hungary": 'hun',
  "iceland": 'isl',
  "india": 'ind',
  "indonesia": 'idn',
  "iran - islamic republic of": 'irn',
  "iraq": 'irq',
  "ireland": 'irl',
  "isle of man": 'imn',
  "israel": 'isr',
  "italy": 'ita',
  "jamaica": 'jam',
  "japan": 'jpn',
  "jersey": 'jey',
  "jordan": 'jor',
  "kazakhstan": 'kaz',
  "kenya": 'ken',
  "kiribati": 'kir',
  "korea - democratic people's republic of": 'prk',
  "korea - republic of": 'kor',
  "kuwait": 'kwt',
  "kyrgyzstan": 'kgz',
  "lao people's democratic republic": 'lao',
  "latvia": 'lva',
  "lebanon": 'lbn',
  "lesotho": 'lso',
  "liberia": 'lbr',
  "libya": 'lby',
  "liechtenstein": 'lie',
  "lithuania": 'ltu',
  "luxembourg": 'lux',
  "macao": 'mac',
  "madagascar": 'mdg',
  "malawi": 'mwi',
  "malaysia": 'mys',
  "maldives": 'mdv',
  "mali": 'mli',
  "malta": 'mlt',
  "marshall islands": 'mhl',
  "martinique": 'mtq',
  "mauritania": 'mrt',
  "mauritius": 'mus',
  "mexico": 'mex',
  "micronesia - federated states of": 'fsm',
  "moldova - republic of": 'mda',
  "monaco": 'mco',
  "mongolia": 'mng',
  "montenegro": 'mne',
  "montserrat": 'msr',
  "morocco": 'mar',
  "mozambique": 'moz',
  "myanmar": 'mmr',
  "namibia": 'nam',
  "nauru": 'nru',
  "nepal": 'npl',
  "netherlands - kingdom of the": 'nld',
  "new caledonia": 'ncl',
  "new zealand": 'nzl',
  "nicaragua": 'nic',
  "niger": 'ner',
  "nigeria": 'nga',
  "niue": 'niu',
  "norfolk island": 'nfk',
  "north macedonia": 'mkd',
  "northern mariana islands": 'mnp',
  "norway": 'nor',
  "oman": 'omn',
  "pakistan": 'pak',
  "palau": 'plw',
  "palestine - state of": 'pse',
  "panama": 'pan',
  "papua new guinea": 'png',
  "paraguay": 'pry',
  "peru": 'per',
  "philippines": 'phl',
  "pitcairn": 'pcn',
  "poland": 'pol',
  "portugal": 'prt',
  "puerto rico": 'pri',
  "qatar": 'qat',
  "romania": 'rou',
  "russian federation": 'rus',
  "rwanda": 'rwa',
  "saint barthélemy": 'blm',
  "saint helena - ascension and tristan da cunha": 'shn',
  "saint kitts and nevis": 'kna',
  "saint lucia": 'lca',
  "saint martin (french part)": 'maf',
  "saint vincent and the grenadines": 'vct',
  "samoa": 'wsm',
  "san marino": 'smr',
  "sao tome and principe": 'stp',
  "saudi arabia": 'sau',
  "senegal": 'sen',
  "serbia": 'srb',
  "seychelles": 'syc',
  "sierra leone": 'sle',
  "singapore": 'sgp',
  "sint maarten (dutch part)": 'sxm',
  "slovakia": 'svk',
  "slovenia": 'svn',
  "solomon islands": 'slb',
  "somalia": 'som',
  "south africa": 'zaf',
  "south georgia and the south sandwich islands": 'sgs',
  "south sudan": 'ssd',
  "spain": 'esp',
  "sri lanka": 'lka',
  "sudan": 'sdn',
  "suriname": 'sur',
  "sweden": 'swe',
  "switzerland": 'che',
  "syrian arab republic": 'syr',
  "tajikistan": 'tjk',
  "tanzania - united republic of": 'tza',
  "thailand": 'tha',
  "timor-leste": 'tls',
  "togo": 'tgo',
  "tokelau": 'tkl',
  "tonga": 'ton',
  "trinidad and tobago": 'tto',
  "tunisia": 'tun',
  "türkiye": 'tur',
  "turkmenistan": 'tkm',
  "turks and caicos islands": 'tca',
  "tuvalu": 'tuv',
  "uganda": 'uga',
  "ukraine": 'ukr',
  "united arab emirates": 'are',
  "united kingdom of great britain and northern ireland": 'gbr',
  "united states of america": 'usa',
  "united states minor outlying islands": 'umi',
  "uruguay": 'ury',
  "uzbekistan": 'uzb',
  "vanuatu": 'vut',
  "venezuela - bolivarian republic of": 'ven',
  "viet nam": 'vnm',
  "virgin islands (british)": 'vgb',
  "virgin islands (u.s.)": 'vir',
  "wallis and futuna": 'wlf',
  "yemen": 'yem',
  "zambia": 'zmb',
  "zimbabwe": 'zwe',
  // Common labels used by proxy subscriptions and Chinese/Vietnamese users.
  'uk': 'gbr',
  'england': 'gbr',
  'britain': 'gbr',
  'america': 'usa',
  'south korea': 'kor',
  'korea': 'kor',
  'russia': 'rus',
  'vietnam': 'vnm',
  'taiwan': 'twn',
  'netherlands': 'nld',
  'the netherlands': 'nld',
  'united kingdom': 'gbr',
  'turkey': 'tur',
  'uae': 'are',
  'czech republic': 'cze',
  '中国': 'chn',
  '香港': 'hkg',
  '台湾': 'twn',
  '日本': 'jpn',
  '韩国': 'kor',
  '新加坡': 'sgp',
  '越南': 'vnm',
  '泰国': 'tha',
  '马来西亚': 'mys',
  '印尼': 'idn',
  '印度': 'ind',
  '美国': 'usa',
  '加拿大': 'can',
  '英国': 'gbr',
  '德国': 'deu',
  '法国': 'fra',
  '俄罗斯': 'rus',
  '澳大利亚': 'aus',
  '土耳其': 'tur',
  '阿联酋': 'are',
  'việt nam': 'vnm',
  'nhật bản': 'jpn',
  'hàn quốc': 'kor',
  'trung quốc': 'chn',
};
